name:                woot
version:             0.0.0.6
synopsis:            Real time group editor without operational transform.
description:         Without operation transform - WOOT.
homepage:            https://github.com/TGOlson/woot-haskell
license:             MIT
license-file:        LICENSE
author:              Tyler Olson
maintainer:          tydotg@gmail.com
category:            Data
extra-source-files:  README.md
github:              TGOlson/woot-haskell

ghc-options: -Wall

library:
  source-dirs: lib
  exposed-modules:
    - Data.Woot
    - Data.Woot.Core
    - Data.Woot.Operation
    - Data.Woot.WChar
    - Data.Woot.WString

default-extensions:
  - TupleSections

tests:
  test:
    main: "Spec.hs"
    source-dirs:
      - spec

    dependencies:
      - hspec
      - woot

dependencies:
  - base <= 5
  - vector
